spring: 
 port: 8081
 jpa:
  hibernate:
   ddl-auto: update
   show_sql: true
   dialect: org.hibernate.dialect.MySQL8Dialect
 datasource: 
  url: jdbc:mysql://localhost:3306/student_management_db  jdbc:h2:mem:student_db
  username: root
  password: admin
 servlet:
  context-path: /StudentManagement
 mvc:
  view:
   prefix: /WEB-INF/views/
   suffix: .jsp  	 	
  sql:
    init:
      mode: always